export const DURATION_UNITS = ['sec', 'min', 'hr', 'days'] as const;

export const TEMPERATURE_UNITS = ['°C', '°F', 'K'] as const;

export const AMOUNT_UNITS = [
  'µL', 'mL', 'L',
  'ng', 'µg', 'mg', 'g', 'kg',
  'nM', 'µM', 'mM', 'M',
  'ng/µL', 'µg/µL', 'mg/mL',
  'U', 'U/µL',
  'x', '%', 'v/v', 'w/v',
  'pmol', 'nmol', 'µmol', 'mmol', 'mol',
  'bp', 'kb',
  'cells', 'cells/mL',
  'CFU', 'CFU/mL',
  'psi', 'rpm',
] as const;

export const EQUIPMENT_LIST = [
  'Autoclave',
  'Balance (analytical)',
  'Balance (top-loading)',
  'Biosafety cabinet',
  'Bunsen burner',
  'Centrifuge',
  'Centrifuge (microcentrifuge)',
  'Centrifuge (ultracentrifuge)',
  'Colony counter',
  'Cuvette',
  'Dry bath / heat block',
  'Electroporator',
  'Flow cytometer',
  'Freezer (-20°C)',
  'Freezer (-80°C)',
  'Fridge (4°C)',
  'Fume hood',
  'Gel documentation system',
  'Gel electrophoresis apparatus',
  'Hemocytometer',
  'Hot plate',
  'Ice bucket',
  'Incubator',
  'Incubator (CO₂)',
  'Incubator (shaking)',
  'Laminar flow hood',
  'Liquid nitrogen dewar',
  'Magnetic stirrer',
  'Microplate reader',
  'Microscope',
  'Microscope (fluorescence)',
  'Micropipette (P2)',
  'Micropipette (P10)',
  'Micropipette (P20)',
  'Micropipette (P200)',
  'Micropipette (P1000)',
  'Multichannel pipette',
  'NanoDrop spectrophotometer',
  'PCR thermocycler',
  'pH meter',
  'Plate shaker',
  'Power supply (electrophoresis)',
  'Qubit fluorometer',
  'Real-time PCR (qPCR) machine',
  'Refrigerated centrifuge',
  'Rotary evaporator',
  'SDS-PAGE apparatus',
  'Shaking incubator',
  'Sonicator',
  'Spectrophotometer',
  'Speed vacuum concentrator',
  'Thermal cycler',
  'Timer',
  'Transilluminator (UV)',
  'Vacuum pump',
  'Vortex mixer',
  'Water bath',
  'Western blot transfer apparatus',
];

export const REAGENT_LIST = [
  'Agarose',
  'Ampicillin',
  'β-mercaptoethanol',
  'Bovine serum albumin (BSA)',
  'Bradford reagent',
  'Calcium chloride (CaCl₂)',
  'Chloramphenicol',
  'DAPI',
  'Deionized water (dH₂O)',
  'DMEM',
  'DMSO',
  'DNA ladder (1 kb)',
  'DNA ladder (100 bp)',
  'DNA loading dye',
  'dNTPs',
  'DTT',
  'EDTA',
  'Ethanol (70%)',
  'Ethanol (100%)',
  'Ethidium bromide',
  'FBS (fetal bovine serum)',
  'GelRed',
  'Glacial acetic acid',
  'Glucose',
  'Glycerol',
  'HCl',
  'HEPES',
  'Isopropanol',
  'IPTG',
  'Kanamycin',
  'LB agar',
  'LB broth',
  'Lysozyme',
  'Magnesium chloride (MgCl₂)',
  'Methanol',
  'NaCl',
  'NaOH',
  'PBS (phosphate-buffered saline)',
  'Penicillin-streptomycin',
  'Phenol-chloroform',
  'Phusion polymerase',
  'Potassium chloride (KCl)',
  'Proteinase K',
  'Restriction enzyme (EcoRI)',
  'Restriction enzyme (BamHI)',
  'Restriction enzyme (HindIII)',
  'Restriction enzyme (XbaI)',
  'Restriction enzyme (SpeI)',
  'Restriction enzyme (PstI)',
  'RNase A',
  'SDS',
  'SOC medium',
  'Sodium acetate',
  'T4 DNA ligase',
  'T4 DNA ligase buffer',
  'Taq polymerase',
  'TBE buffer',
  'TE buffer',
  'Tris-HCl',
  'Triton X-100',
  'Trypan blue',
  'Trypsin-EDTA',
  'Tween 20',
  'X-gal',
];
